# Generated by Django 5.0.2 on 2024-02-29 14:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1024, 768], upload_to='media/avatars'),
        ),
    ]
