# Generated by Django 5.0.2 on 2024-02-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tasks_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='task',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Задачи по теме'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='module.js',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module.js', verbose_name='Модуль'),
        ),
    ]
