# Generated by Django 5.0.2 on 2024-03-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module.js',
            old_name='slug',
            new_name='module_slug',
        ),
    ]
