# Generated by Django 5.0.2 on 2024-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_slug_module_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='module.js',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
