# Generated by Django 5.0.2 on 2024-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_module_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'verbose_name': 'Под-тема', 'verbose_name_plural': 'Подтемы'},
        ),
        migrations.AddField(
            model_name='subtopic',
            name='home_tasks',
            field=models.TextField(null=True, verbose_name='Домашние задачи'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='link',
            field=models.CharField(max_length=500, null=True, verbose_name='Ссылка на google-форму для ответов'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
