# Generated by Django 5.0.2 on 2024-03-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_useranswer_topic_remove_useranswer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='slug',
            new_name='topic_slug',
        ),
    ]
