# Generated by Django 5.0.2 on 2024-03-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_slug_topic_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='slug',
            new_name='subtopic_slug',
        ),
    ]
