# Generated by Django 5.0.2 on 2024-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_slug_subtopic_subtopic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='topic',
            name='home_tasks',
            field=models.TextField(null=True, verbose_name='Домашние задачи'),
        ),
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.CharField(max_length=500, null=True, verbose_name='Ссылка на google-форму для ответов'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.CharField(max_length=300, null=True, verbose_name='Запись занятия'),
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
