# Generated by Django 5.0.2 on 2024-03-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_topic_content_topic_home_tasks_topic_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('content', models.TextField(null=True, verbose_name='Содержание')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Поддемы',
            },
        ),
    ]
