# Generated by Django 5.0.2 on 2024-03-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_topic_content_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
