# Generated by Django 5.0.2 on 2024-03-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_subtopic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='home_tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Домашние задачи'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на google-форму для ответов'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Запись занятия'),
        ),
    ]
